### ISSUE TITLE
可否加入对抗模式

### ISSUE THREAD

**Issue by setchin** [fantasylidong/AnneZonemod#12]
东哥好，想尝试在服务器里把稳定服保留的Zonemod加进去，试了一下没有完全成功。
我的想法是在cfg/cfgogl里建一个zonemod文件夹，然后把之前的插件和配置文件放到相应位置，之后再用sm_forcematch zonemod切换模式（看了下!match !vote命令的源码 大概是用这个原理操作的吧）。
尝试之后可以加载配置并且自动重启地图，模式大概确实也变成对抗了，用sm plugins list可以看到插件应该也是加载了（共140多个，数量上和cfg写的好像差不多，但是没有细看）但是看不到比赛前的准备面板，玩家无法按m选择阵营，特感方无法复活，只有刷出tank的时候可以操纵克，一关打完倒确实会交换阵营。过程中tank的血量是9000，对抗的克血量乘了1.5倍，这么看好像是加载了某些让tank_health变成6000的命令，是否是一些药役的配置没有卸载干净呢？

**Comment by fantasylidong** [comment]
有很多插件改过，你不能用这个项目的版本，你应该弄一个新文件夹，把zonemod要用的放里面，并且改插件加载位置
其次我的confogl并没有加载generalfix.cfg文件，ownplugins里倒是有一部分，但是不完整，所以你要把generalfix那个文件里的插件放到shared_plugin里最前面的位置，并且不要加载ownplugins，或者你自己改一下confogl那个插件
还有你不要在server.cfg文件里写sm_fm强制修改配置，这个指令被我改了不会鉴别模式是否已经加载，具体怎么改看一下我的server.cfg

应该是可以不改代码实现的，如果觉得我这种模式不好，你就自己改一下confogl插件吧

**Comment by fantasylidong** [comment]
我自己是没有兴趣添加，我每个服务器都用的docker，可以自定义使用的插件包，我不会添加所有模式在一个插件包里，对于我来说维护麻烦。
你如果有兴趣可以fork一份自己修改一下看一下别人是否需要

**Comment by setchin** [comment]
> 有很多插件改过，你不能用这个项目的版本，你应该弄一个新文件夹，把zonemod要用的放里面，并且改插件加载位置 其次我的confogl并没有加载generalfix.cfg文件，ownplugins里倒是有一部分，但是不完整，所以你要把generalfix那个文件里的插件放到shared_plugin里最前面的位置，并且不要加载ownplugins，或者你自己改一下confogl那个插件 还有你不要在server.cfg文件里写sm_fm强制修改配置，这个指令被我改了不会鉴别模式是否已经加载，具体怎么改看一下我的server.cfg
> 
> 应该是可以不改代码实现的，如果觉得我这种模式不好，你就自己改一下confogl插件吧

哦 我之前就把zonemod所有的插件单独列了个文件夹保存原版的插件，generalfixes.cfg我也加上去了 不过server.cfg我确实没试过，尝试一下

**Comment by fantasylidong** [comment]
准备再次重构插件包，完全按照对抗插件包制作，请关注项目： https://github.com/fantasylidong/CompetitiveWithAnne

**Comment by fantasylidong** [comment]
重构完成，试了一下没啥问题

**Comment by setchin** [comment]
> 重构完成，试了一下没啥问题

感谢服主
